"""Regenerate the vault's folder indexes and daily/weekly note navigation.

Keeps routine-generated notes connected in the Obsidian graph without anyone
hand-maintaining links. Safe to re-run any time; output is deterministic, so a
run with nothing new changes nothing. Run by the daily-repo-sync routine
(prompts/DAILY.md) right after the repo doc sync.

Writes:
  reports/INDEX.md   every report, grouped by kind (eng-loc, eng-mini, cloud/<routine>, ...)
                     then by repo, newest first
  projects/INDEX.md  every project doc, grouped by folder
  notes/INDEX.md     every daily and weekly note, newest first
  notes/<dated>.md   one nav line under the H1 (prev / next day, its ISO week;
                     weekly notes list their days), marked <!-- nav --> so it is
                     replaced in place, never duplicated

Usage:  python agent/scripts/build-vault-indexes.py [--check]
        --check  exit 1 if anything would change (no writes)
"""
import datetime as dt
import os
import re
import sys
from collections import defaultdict

VAULT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
NAV = "<!-- nav -->"
DAY = re.compile(r"^(\d{4}-\d{2}-\d{2})\.md$")
WEEK = re.compile(r"^(\d{4})-W(\d{2})\.md$")
DATE_IN_NAME = re.compile(r"(\d{4}-\d{2}(?:-\d{2})?)")
changed = []
# repos renamed since older reports were written (report name -> current hub)
RENAMED = {"overseer": "vigil", "auto-apply-plugin": "ats-fill"}


def write(path, text):
    text = text.rstrip("\n") + "\n"
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old is not None and old.replace("\r\n", "\n") == text:
        return
    changed.append(os.path.relpath(path, VAULT))
    if "--check" not in sys.argv:
        nl = "\r\n" if old and "\r\n" in old else "\n"
        with open(path, "w", encoding="utf-8", newline="") as f:
            f.write(text.replace("\n", nl))


def md_files(folder):
    root = os.path.join(VAULT, folder)
    out = []
    for dp, dn, fn in os.walk(root):
        dn[:] = sorted(d for d in dn if not d.startswith("."))
        for f in fn:
            if f.endswith(".md") and f != "INDEX.md":
                out.append(os.path.relpath(os.path.join(dp, f), VAULT).replace(os.sep, "/"))
    return sorted(out)


def link(path, label=None):
    target = path[:-3]
    return f"[[{target}|{label}]]" if label else f"[[{target}]]"


def header(title, blurb):
    return (f"# {title}\n\n> 🧭 [[AGENT-MAIN]] · [[REPOS-INDEX|Repo Docs Index]] · "
            f"[[reports/INDEX|Reports]] · [[projects/INDEX|Projects]] · [[notes/INDEX|Notes]]\n\n"
            f"_Generated by `agent/scripts/build-vault-indexes.py`; do not edit by hand._ {blurb}\n")


# ---------- reports/INDEX.md ----------
def report_kind_and_subject(path):
    rel = path[len("reports/"):]
    if "/" in rel:  # reports/cloud/<routine>/<date>.md
        return "/".join(rel.split("/")[:-1]), None
    stem = rel[:-3]
    stem = DATE_IN_NAME.sub("", stem).strip("-")
    for kind in ("eng-loc-high-LOC", "eng-loc", "eng-mini"):
        if stem.startswith(kind + "-") or stem == kind:
            subject = stem[len(kind):].strip("-") or "(unnamed)"
            return kind, subject
    return stem or "(misc)", None


def date_key(path):
    m = DATE_IN_NAME.findall(os.path.basename(path))
    return m[-1] if m else ""


groups = defaultdict(lambda: defaultdict(list))
for p in md_files("reports"):
    kind, subject = report_kind_and_subject(p)
    groups[kind][subject].append(p)

lines = [header("Reports Index", "Every report under `reports/`, grouped by kind, newest first.")]
for kind in sorted(groups):
    lines.append(f"\n## {kind}\n")
    subjects = groups[kind]
    for subject in sorted(subjects, key=lambda s: (s is None, s or "")):
        files = sorted(subjects[subject], key=date_key, reverse=True)
        if subject is None:
            for f in files:
                lines.append(f"- {link(f, date_key(f) or os.path.basename(f)[:-3])}")
        else:
            repo_hub = f"repos/{RENAMED.get(subject, subject)}.md"
            name = link(repo_hub, subject) if os.path.exists(os.path.join(VAULT, repo_hub)) else subject
            items = ", ".join(link(f, date_key(f) or "undated") for f in files)
            lines.append(f"- **{name}**: {items}")
write(os.path.join(VAULT, "reports", "INDEX.md"), "\n".join(lines))

# ---------- projects/INDEX.md ----------
proj = defaultdict(list)
for p in md_files("projects"):
    rel = p[len("projects/"):]
    proj[rel.split("/")[0] if "/" in rel else ""].append(p)
lines = [header("Projects Index", "Every doc under `projects/`, grouped by folder.")]
for folder in sorted(proj, key=lambda f: (f != "", f.lower())):
    lines.append(f"\n## {folder or 'Top level'}\n")
    for f in proj[folder]:
        lines.append(f"- {link(f, f[len('projects/'):][:-3])}")
write(os.path.join(VAULT, "projects", "INDEX.md"), "\n".join(lines))

# ---------- notes: INDEX + per-note nav ----------
notes_dir = os.path.join(VAULT, "notes")
days, weeks, other = [], [], []
for f in sorted(os.listdir(notes_dir)):
    if not f.endswith(".md") or f == "INDEX.md":
        continue
    (days if DAY.match(f) else weeks if WEEK.match(f) else other).append(f)


def iso_week(day_name):
    y, w, _ = dt.date.fromisoformat(day_name[:10]).isocalendar()
    return f"{y}-W{w:02d}"


week_days = defaultdict(list)
for d in days:
    week_days[iso_week(d)].append(d[:-3])


def set_nav(fname, nav):
    path = os.path.join(notes_dir, fname)
    raw = open(path, encoding="utf-8").read()
    body = [l for l in raw.replace("\r\n", "\n").split("\n") if NAV not in l]
    h1 = next((i for i, l in enumerate(body[:15]) if re.match(r"^#\s", l)), None)
    if h1 is None:
        while body and body[0].strip() == "":
            body = body[1:]
        new = [nav, ""] + body
    else:
        rest = body[h1 + 1:]
        while rest and rest[0].strip() == "":
            rest = rest[1:]
        new = body[:h1 + 1] + ["", nav, ""] + rest
    out = "\n".join(new).rstrip("\n") + "\n"
    if out != raw.replace("\r\n", "\n"):
        changed.append(os.path.relpath(path, VAULT))
        if "--check" not in sys.argv:
            nl = "\r\n" if "\r\n" in raw else "\n"
            with open(path, "w", encoding="utf-8", newline="") as fh:
                fh.write(out.replace("\n", nl))


for i, d in enumerate(days):
    parts = [f"[[notes/INDEX|Notes]]"]
    if i > 0:
        parts.append(f"← [[notes/{days[i - 1][:-3]}|{days[i - 1][:-3]}]]")
    if i + 1 < len(days):
        parts.append(f"[[notes/{days[i + 1][:-3]}|{days[i + 1][:-3]}]] →")
    wk = iso_week(d)
    if f"{wk}.md" in weeks:
        parts.append(f"week [[notes/{wk}|{wk}]]")
    set_nav(d, "> 🧭 " + " · ".join(parts) + " " + NAV)
for w in weeks:
    wk = w[:-3]
    parts = ["[[notes/INDEX|Notes]]"] + [f"[[notes/{d}|{d}]]" for d in week_days.get(wk, [])]
    set_nav(w, "> 🧭 " + " · ".join(parts) + " " + NAV)

lines = [header("Notes Index", "Daily and weekly notes, newest first.")]
lines.append("\n## Weekly\n")
lines += [f"- {link('notes/' + w)}" for w in sorted(weeks, reverse=True)]
lines.append("\n## Daily\n")
lines += [f"- {link('notes/' + d)}" for d in sorted(days, reverse=True)]
if other:
    lines.append("\n## Other\n")
    lines += [f"- {link('notes/' + o)}" for o in other]
write(os.path.join(notes_dir, "INDEX.md"), "\n".join(lines))

print(f"{'would change' if '--check' in sys.argv else 'changed'}: {len(changed)} file(s)")
for c in changed:
    print("  " + c.replace(os.sep, "/"))
if "--check" in sys.argv and changed:
    sys.exit(1)
