"""Link routine-generated notes into the vault graph through meaningful hubs.

No flat INDEX files: every note hangs off the hub it belongs to, so an agent
reaches anything from VAULT-MAP in a few hops and the Obsidian graph shows one
cluster per repo/project instead of a few giant stars. Safe to re-run any time;
output is deterministic, so a run with nothing new changes nothing. Run by the
daily-repo-sync routine (prompts/DAILY.md) right after the repo doc sync.

Rules (naming conventions first, `up:` frontmatter for anything else):
  reports/<kind>-<repo>-<date>.md   nav line: up to repos/<repo> hub, prev/next in
                                    the same kind+repo. The hub's Vault links
                                    block links the latest one.
  reports/<kind>-<date>.md,         nav line: prev/next in the same kind. VAULT-MAP
  reports/cloud/<routine>/<date>.md links the latest one.
  projects/KB/<repo>-overview.md    linked from the repos/<repo> hub.
  projects/<Folder>/**.md           linked from a children block in the folder hub: an
                                    existing projects/<Folder>.md, else projects/<Folder>-hub.md
                                    (created as a stub; the suffix keeps names unique).
  projects/*.md, notes/<other>.md   linked from VAULT-MAP.
  notes/<YYYY-MM-DD>.md, <YYYY>-W<ww>.md
                                    nav line: prev/next + week (weeks list their days).
                                    VAULT-MAP links the latest of each.
  repos/<repo>.md                   linked from VAULT-MAP; its Vault links block links the
                                    mirrored README, KB overview and latest reports.

VAULT-MAP.md is the vault home (created with a short intro if missing). Its body is
the generated block; AGENT-MAIN stays the delivery-process guide and links to it.

Writes only two kinds of generated text, both replaced in place and never
duplicated:
  a nav line under the H1        marked <!-- nav -->
  a block at the end of a hub    between <!-- vault-links:start/end -->

Anything that fits none of the rules: give it `up: "[[parent]]"` frontmatter, which
Obsidian counts as a link. scripts/find-orphans.py reports what is still loose.

Usage:  python agent/scripts/build-vault-indexes.py [--check]
        --check  exit 1 if anything would change (no writes)
"""
import datetime as dt
import os
import re
import sys
from collections import defaultdict

VAULT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CHECK = "--check" in sys.argv
NAV = "<!-- nav -->"
START, END = "<!-- vault-links:start -->", "<!-- vault-links:end -->"
GENERATED = "_Generated by `scripts/build-vault-indexes.py`; edits inside this block are overwritten._"
DAY = re.compile(r"^(\d{4}-\d{2}-\d{2})\.md$")
WEEK = re.compile(r"^(\d{4})-W(\d{2})\.md$")
DATE_IN_NAME = re.compile(r"(\d{4}-\d{2}(?:-\d{2})?)")
REPO_KINDS = {"eng-loc-high-LOC": "High-LOC report", "eng-loc": "LOC report", "eng-mini": "MINI report"}
# repos renamed since older reports were written (report name -> current hub)
RENAMED = {"overseer": "vigil", "auto-apply-plugin": "ats-fill"}
changed = []


# ---------- file helpers ----------
def path_of(rel):
    return os.path.join(VAULT, *rel.split("/"))


def exists(rel):
    return os.path.exists(path_of(rel))


def read(rel):
    """Return (text with \\n newlines, original newline style)."""
    if not exists(rel):
        return None, "\n"
    raw = open(path_of(rel), encoding="utf-8").read()
    return raw.replace("\r\n", "\n"), "\r\n" if "\r\n" in raw else "\n"


def write(rel, text, nl="\n"):
    text = text.rstrip("\n") + "\n"
    old, _ = read(rel)
    if old == text:
        return
    changed.append(rel)
    if not CHECK:
        with open(path_of(rel), "w", encoding="utf-8", newline="") as f:
            f.write(text.replace("\n", nl))


def md_files(folder):
    out = []
    for dp, dn, fn in os.walk(path_of(folder)):
        dn[:] = sorted(d for d in dn if not d.startswith("."))
        for f in fn:
            if f.endswith(".md"):
                out.append(os.path.relpath(os.path.join(dp, f), VAULT).replace(os.sep, "/"))
    return sorted(out)


def link(rel, label=None):
    target = rel[:-3] if rel.endswith(".md") else rel
    return f"[[{target}|{label}]]" if label else f"[[{target}]]"


def date_key(rel):
    m = DATE_IN_NAME.findall(os.path.basename(rel))
    return m[-1] if m else ""


def set_nav(rel, parts):
    """Put `> 🧭 parts <!-- nav -->` under the H1 (or drop it when parts is empty)."""
    text, nl = read(rel)
    if not parts and NAV not in text:
        return
    body = [l for l in text.split("\n") if NAV not in l]
    h1 = next((i for i, l in enumerate(body[:15]) if re.match(r"^#\s", l)), None)
    head, rest = (body[:h1 + 1], body[h1 + 1:]) if h1 is not None else ([], body)
    # frontmatter must stay first when there is no H1
    if h1 is None and rest[:1] == ["---"] and "---" in rest[1:]:
        close = rest.index("---", 1)
        head, rest = rest[:close + 1], rest[close + 1:]
    while rest and rest[0].strip() == "":
        rest = rest[1:]
    nav = ["", "> 🧭 " + " · ".join(parts) + " " + NAV] if parts else []
    new = head + nav + ([""] if head or nav else []) + rest
    while new and new[0] == "":
        new = new[1:]
    write(rel, "\n".join(new), nl)


def set_block(rel, lines):
    """Replace (or append) the vault-links block at the end of a hub note."""
    text, nl = read(rel)
    text = re.sub(rf"\n*{re.escape(START)}.*?{re.escape(END)}\n*", "\n", text, flags=re.S).rstrip("\n")
    if lines:
        text += "\n\n" + "\n".join([START] + lines + [END])
    write(rel, text, nl)


# ---------- reports ----------
def report_kind_and_subject(rel):
    rest = rel[len("reports/"):]
    if "/" in rest:  # reports/cloud/<routine>/<date>.md
        return "/".join(rest.split("/")[:-1]), None
    stem = DATE_IN_NAME.sub("", rest[:-3]).strip("-")
    for kind in REPO_KINDS:
        if stem.startswith(kind + "-") or stem == kind:
            return kind, stem[len(kind):].strip("-") or "(unnamed)"
    return stem or "(misc)", None


hubs = [p for p in md_files("repos") if p.count("/") == 1]
HUB_BY_NAME = {os.path.basename(h)[:-3].lower(): h for h in hubs}  # exact case, e.g. repos/Odysseus.md


def repo_hub(name):
    return HUB_BY_NAME.get(RENAMED.get(name, name).lower())


chains = defaultdict(list)
for p in md_files("reports"):
    if os.path.basename(p) != "INDEX.md":
        chains[report_kind_and_subject(p)].append(p)

hub_lines = defaultdict(list)   # repos/<x>.md -> block lines
latest_reports = []             # (label, rel) for VAULT-MAP
for (kind, subject), files in sorted(chains.items(), key=lambda kv: (kv[0][0], kv[0][1] or "")):
    files.sort(key=lambda f: (date_key(f), f))
    hub = repo_hub(subject) if subject else None
    for i, f in enumerate(files):
        parts = [link(hub, subject)] if hub else []
        if i > 0:
            parts.append("← " + link(files[i - 1], date_key(files[i - 1]) or "undated"))
        if i + 1 < len(files):
            parts.append(link(files[i + 1], date_key(files[i + 1]) or "undated") + " →")
        set_nav(f, parts)
    newest = files[-1]
    label = date_key(newest) or os.path.basename(newest)[:-3]
    if hub:
        hub_lines[hub].append((REPO_KINDS[kind], newest, label))
    else:
        latest_reports.append((f"{kind} · {subject}" if subject else kind, newest, label))

# ---------- repo hubs ----------
kb = {}
for p in md_files("projects/KB"):
    m = re.match(r"^(.*)-overview\.md$", os.path.basename(p))
    if m and repo_hub(m.group(1)):
        kb[repo_hub(m.group(1))] = p

for hub in hubs:
    name = os.path.basename(hub)[:-3]
    lines = []
    if exists(f"repos/{name}/README.md"):
        lines.append(f"- Docs: {link(f'repos/{name}/README.md', 'README')} (every doc hangs off its Docs Index)")
    if hub in kb:
        lines.append(f"- Overview: {link(kb[hub], 'KB overview')}")
    for label, rel, date in sorted(hub_lines.get(hub, [])):
        lines.append(f"- Latest {label}: {link(rel, date)} (older ones chain from it)")
    set_block(hub, ["## Vault links", "", GENERATED, ""] + lines if lines else [])

# tracked = the Tracked table in projects/scope.md (the repo registry every routine reads)
text, _ = read("projects/scope.md")
tracked = re.findall(r"^\| ([a-z0-9-]+) \|", text.split("## Tracked", 1)[-1].split("\n## ", 1)[0], re.M)
tracked_hubs = sorted({h for h in (repo_hub(r) for r in tracked) if h})
other_hubs = [h for h in hubs if h not in tracked_hubs]

# ---------- projects ----------
folders = defaultdict(list)
for p in md_files("projects"):
    rest = p[len("projects/"):]
    if "/" not in rest or p in kb.values() or os.path.basename(p) == "INDEX.md":
        continue
    folders[rest.split("/")[0]].append(p)
for folder, files in sorted(folders.items()):
    # an existing projects/<Folder>.md note (e.g. ARGUS) is the hub; otherwise <Folder>-hub.md, a
    # distinct name so it never collides with prompts/<Folder>.md in [[wikilinks]] or the graph
    hub = f"projects/{folder}.md" if exists(f"projects/{folder}.md") else f"projects/{folder}-hub.md"
    if not exists(hub):
        write(hub, f"# {folder}\n\nFolder hub for `projects/{folder}/`. Add context above the generated block.")
    lines = [f"- {link(f, f[len(folder) + 10:-3])}" for f in files]
    set_block(hub, ["## Vault links", "", GENERATED, ""] + lines)
top_projects = [p for p in md_files("projects") if p.count("/") == 1 and not p.endswith("/INDEX.md")]
if CHECK:  # stub hubs a real run would create
    top_projects = sorted(set(top_projects) | {f"projects/{f}.md" if exists(f"projects/{f}.md")
                                               else f"projects/{f}-hub.md" for f in folders})

# ---------- notes ----------
names = sorted(f for f in os.listdir(path_of("notes")) if f.endswith(".md") and f != "INDEX.md")
days = [f[:-3] for f in names if DAY.match(f)]
weeks = [f[:-3] for f in names if WEEK.match(f)]
other_notes = [f"notes/{f}" for f in names if not DAY.match(f) and not WEEK.match(f)]


def iso_week(day):
    y, w, _ = dt.date.fromisoformat(day).isocalendar()
    return f"{y}-W{w:02d}"


def chain(items, i):
    parts = []
    if i > 0:
        parts.append("← " + link(f"notes/{items[i - 1]}", items[i - 1]))
    if i + 1 < len(items):
        parts.append(link(f"notes/{items[i + 1]}", items[i + 1]) + " →")
    return parts


for i, d in enumerate(days):
    wk = iso_week(d)
    set_nav(f"notes/{d}.md", chain(days, i) + ([f"week {link(f'notes/{wk}', wk)}"] if wk in weeks else []))
for i, w in enumerate(weeks):
    set_nav(f"notes/{w}.md", chain(weeks, i) + [link(f"notes/{d}", d) for d in days if iso_week(d) == w])

# ---------- VAULT-MAP (the vault home) ----------
home = ["## Vault map", "", GENERATED, ""]
latest = []
if days:
    latest.append(f"{link('notes/' + days[-1], days[-1])} (daily)")
if weeks:
    latest.append(f"{link('notes/' + weeks[-1], weeks[-1])} (weekly)")
if latest:
    home.append("- **Latest notes:** " + " · ".join(latest) + " (older ones chain from these)")
home.append("- **Repos** ([[projects/scope|Scope]] tracked; each hub links its README, KB overview and latest reports): "
            + " · ".join(link(h, os.path.basename(h)[:-3]) for h in tracked_hubs))
if other_hubs:
    home.append("- **Other repo hubs:** " + " · ".join(link(h, os.path.basename(h)[:-3]) for h in other_hubs))
if latest_reports:
    home.append("- **Latest reports** (older ones chain from these):")
    home += [f"  - {label}: {link(rel, date)}" for label, rel, date in latest_reports]
if top_projects:
    home.append("- **Projects:** " + " · ".join(link(p, os.path.basename(p)[:-3]) for p in top_projects))
if other_notes:
    home.append("- **Other notes:** " + " · ".join(link(p, os.path.basename(p)[:-3]) for p in other_notes))
if not exists("VAULT-MAP.md"):
    write("VAULT-MAP.md", "# Vault Map\n\nEntry point to this vault: start here, then follow a hub. "
          "Process guide: [[AGENT-MAIN]] · conventions: [[README|Vault README]].")
set_block("VAULT-MAP.md", home)
set_block("AGENT-MAIN.md", [])  # the map lived here until 2026-09-25

changed = list(dict.fromkeys(changed))
print(f"{'would change' if CHECK else 'changed'}: {len(changed)} file(s)")
for c in changed:
    print("  " + c)
if CHECK and changed:
    sys.exit(1)
